INSERT INTO time_tracking_db.Area VALUES (4, 'CES', 'A');

UPDATE time_tracking_db.User SET area_id = 4 WHERE area_id = 2 AND GAD_ID IN (
'beatriz.montilla',
'BEATRIZ.TERREU',
'CAMILALUCIA.OREILLY',
'CARLOS.ALONSO',
'CARLOTTA.BIAGGI',
'CLARA.BERTRAN',
'C.BOLDIZSAR',
'DANIELLE.EASTON',
'DAVID.IBANEZ',
'D.PEDROSBASSOLS',
'EMANUEL.POPESCU',
'E.FERNANDEZLIEDER',
'F.SAGAZSERRANO',
'HELENA.HERNANDEZ',
'IONA.MANYOSES',
'IVAN.DELRIO',
'J.CARCASMULLOR',
'KATHARINAVIOLA.ROSSI',
'larissaluise.marx',
'LEO.GRIGNE',
'MARC.GARRIGAGEA',
'm.buitragoescobar',
'mariana.duarte',
'michaela.jelinkova',
'MICHEL.LORO1',
'MIGUEL.SAAVEDRA',
'momi.tartarelli',
'm.argueellovargas',
'NICOLE.BTESH',
'n.kokot',
'OLGA.GORCHSNOTIVOLI',
'oliver.stephens1',
'OSCAR.MORALES',
'p.tibrewala',
'rocio.fernandez2',
'sara.rodrigues1',
'stefano.sabatino',
'TERESA.RIBAS'
);

UPDATE time_tracking_db.Project SET area_id = 4 WHERE area_id = 2 AND name IN (
'Admin Tasks (Rocio)',
'App Zurich Risk Solutions',
'Bank Distribution BU Switzerland',
'Bank Holiday',
'Brand Architecture BAU',
'Brand Center O365 Add-in',
'Bright Design',
'Broker Concierge ',
'BU Canada - Middle package proposition',
'BU Middle East - Portals',
'BU TDC HR - Design Assets',
'BU TDC Internal Communications - Design',
'BU TDC Internal Communications - WeAreTDC',
'BU TDC Internal Operations - Design',
'BU Z Foundation Templates',
'CES Events',
'CI Digital IP MIA Redesign',
'Claims on Zurich.ch ',
'Claims Remote Collaboration',
'CLP CX/UX/UI',
'CLP Naming',
'Commercial Insurance small requests',
'Content & Web Editing',
'Corwd compass',
'Creative Services',
'Creative Services Quai Support',
'Customer Academy',
'Customer Segmentation',
'CX - CI workshops',
'CX - Claims Lab',
'CX - Claims TOM',
'CX - Community of Practice',
'CX - Customer Academy ',
'CX - HR Brand',
'CX - IoT Machinery Breakdown',
'CX - Mastery Program',
'CX Design',
'CX Innovation Framework',
'CX Toolkit',
'DDC Design Studio DDC Internal Project and Assets',
'DDC Design Studio DDC UX/UI Internal Assets Projects',
'DDC Desing Studio Internal Team Meetings',
'DDC GF App Mktg Team Meetings',
'DDC Lean Trainings',
'Dealership Portal Redesign',
'Design Studio Cloud CoE',
'Design Studio DDC Visual Assets',
'Design Studio SMI Design Assets',
'Design support CX Innovation',
'Desing Studio Team GCO meetings',
'Digitalization of middle office',
'DSM',
'DSM - IT',
'EGS - Water Bottle',
'Employer Value Proposition Scrum Support',
'Find',
'GBP Brand Definition',
'GBP Slide - MasterBrand',
'GCO Airport Poster',
'GCO BAU Creative Services ',
'GCO BlueRoom',
'GCO Brand Req - Design Assets',
'GCO BVI - Digital Workstream',
'GCO BVI - Guidelines DDC Support',
'GCO BVI - O365 Templates',
'GCO CCE Journey design (Claims)',
'GCO Commercial Services Naming',
'GCO Customer Academy Design',
'GCO Design assets (non Prj related)',
'GCO Digitzation',
'GCO Innovation Portal',
'GCO IT Mgmt',
'GCO LucernFestival Poster',
'GCO Managment/Demand',
'GCO Other Creative Services',
'GCO- PPT Design support',
'GCO Quai Zurich - Customer Journeys',
'GCO Slides Insights Framework',
'GCO SM Summer Posts',
'GCO Sustainability Icons',
'GCO TOM CVP',
'GEMS uplift',
'GF App Champions',
'GF Group Audit Design',
'GF GSIBD - ZIC - Design Assets',
'GF GSIDB MTD MyWallet BCN',
'GF GSIDB MTD MyWallet CH',
'GF GSIDB MTD Support BCN',
'GF GSIDB MTD Support CH',
'GF GSIDB WWF Event',
'GF GSIDB ZIWC Design Startup Contest',
'GF ZIMS Apps ASO',
'GF ZIMS COVID19 App',
'GF ZIMS New App Strategy (COVID19 impact)',
'GF ZIMS Tiaki',
'Global Finance Small/Video Requests',
'Group Comms Small/Video Requests',
'Group General Counsel Small Requests',
'Group Investments- Design Assets',
'Group Ops Evolve Icons',
'GS Strategy Memos and ppt',
'Holidays',
'HR Onboarding UX',
'Hubspot',
'Illness',
'IT Sourcing Strategy Icons',
'ITS - ZH Search',
'ITS Apps Distribution',
'ITS Dublin Hub',
'ITS WE- App Distribution Tech Support',
'ITS WE Office Anywhere Mkt Material',
'Leadership Program Design',
'LiveWell Mkt Strategy',
'LiveWell Web ',
'Livewell website ',
'Location Insights',
'Machinery breakdown',
'Middle Market Renewal',
'My Life MVP ',
'MyLife',
'MyLife Landing page',
'MyZNA',
'Naming Commercial Services',
'RE Services Portal',
'Salesforce MVP',
'SME',
'SME Tower',
'SoMe ATC Alerts',
'SoMe ATC Domain Monitoring',
'SoMe ATC Global Accounts',
'SoMe ATC New Projects',
'SoMe ATC Partner Paid Posts',
'SoMe ATC Team Meetings',
'SoMe ATC Transformation',
'SoMe ATC Webdesk',
'SoMe SMI Alerts',
'SoMe SMI Business Engagement',
'SoMe SMI COVID19 Report',
'SoMe SMI Daily Scan - Monitoring',
'SoMe SMI Dashboard developement',
'SoMe SMI GCO Meetings',
'SoMe SMI GCO Projects',
'SoMe SMI Management',
'SoMe SMI PM Chatbot Compliance',
'SoMe SMI Reporting',
'SoMe SMI Sprinklr',
'SoMe SMI Stakeholder Meetings (INT/EXT)',
'SoMe SMI Team Meetings',
'SoMe SMI Workplace FB',
'Sos Bluefox (New)',
'SoS Communication & Digital Community Calls',
'SoS Content Mgmt',
'SoS Conversational UI Strategy',
'SoS Digital Mailbox',
'SoS LivePerson',
'SoS Project Mgmt',
'SoS Web&App Editing',
'SoS Wellcare Support Malaysia',
'Sourcing & Procurement Small/Video request',
'SP Intranet UX Design',
'Sprinklr',
'TDC internal support (COVID)',
'TDC website re-design',
'Training',
'Transformation and Technology Small request',
'UX/UI',
'VDS Creative Services',
'VDS dummy',
'Wage Collection',
'WCM - News Releases',
'WCM - Newsletters',
'WCM - Results Publication',
'WCM - Team Meetings ',
'WCM - Zurich.com Requests',
'Web Portals UX/UI designs ',
'Wellcare Naming ',
'Z. Luxembourg Website',
'ZCAM CAP',
'ZCAM Reputation Platform',
'ZING IE',
'ZNA D&PM Portals',
'ZNA DSM Library ',
'ZSuite',
'ZSuite IT',
'ZSuite ZWP PM Support',
'Zurich International Marketing Websites',
'Zurich Mastery Program Supervision ',
'Zurich Places App Design',
'ZWP - Benelux Site',
'ZWP - Web Editing Support',
'ZWP Back End Support',
'ZWP Design support',
'ZWP Front End Support',
'ZWP IT'
);

UPDATE time_tracking_db.Program SET area_id = 4 WHERE area_id = 2 AND name IN (
'BU CH',
'BU SP',
'BU TDC',
'BU Zfoundation',
'BU CI Commercial Insurance',
'CES',
'GCO',
'GF GSIDB',
'GF INM',
'GF Sourc. & Proc.',
'GCO Apps',
'ITS DUBHUB',
'PMO',
'CES SoMe ATC',
'CES SoMe SMI',
'GF Group Audit',
'GF GOPS',
'GF HR',
'ITS',
'BU ZNA',
'GROUP GENERAL COUNSEL',
'Transformation and Technology',
'EGS – Creative requests',
'HR',
'GTO',
'GLOBAL HR',
'Group comms',
'BU Zurich International',
'BU Luxembourg',
'My Life',
'BU Switzerland',
'CES Ancillary',
'ZWP',
'GTO - DDC',
'GCO-CXINN',
'ZGV',
'GCO IT Ancillary',
'Global Ventures',
'BU Italy',
'Z Foundation',
'BU IPZ',
'GDP',
'GDP IAM Application',
'APAC',
'BTO'
);